language: node_js
services:
- rabbitmq
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libsdl1.2-dev
    - libgif-dev
    - libjson-glib-dev
    - libglib2.0-dev
    - libpango1.0-dev
env:
  global:
  - AMAZON_API_BUCKET=the-grid-img
  - AMAZON_API_REGION=us-west-2
  - secure: lkm/6WpxNLhqHol6hQ4mkcoezFfrHtcFcD4XeFpLXorQeoZJSQ3e7Jf90t+6TY53rAgsdplCUG1p4Cth6PD6P6fQWpCVIJ2o4dWn6TJLUXLizzGHo8H6pSZclwLWGToKN6Su2i6Ik9t//T0XGzGaKGI3kqrPo3ybCLMtGuQfYIc=
  - secure: sMuerVUrthvDgfNGnWcvE11kKtQUNw8/VvIVAYNiYXKIjhiHKVXOvdLNca3jh1WUE7FM4R9LglqJMhgYmS+MBqY2heYaRb7FUfEk0TzK54qnYkXlEvMwmIzWYShkqqv1hqNCuwfW1IgWcVYSMSeE6JoJx+sSaBXmpYWY8AJ4raM=
node_js:
- '4.6'
before_script:
- psql -c 'create database imgflo_test;' -U postgres
- ./node_modules/.bin/knex migrate:latest
script:
- export IMGFLO_TESTS_PERFORMANCE=1
- export IMGFLO_BROKER_URL=amqp://localhost
- export IMGFLO_WORKER=subprocess
- export DATABASE_URL=postgres://postgres:@localhost/imgflo_test
- export POSTGRES_NOSSL=1
- make travis-deps
- make release RELOCATE_DEPS=true
